### PR TITLE
Merged branch

### PR DESCRIPTION
**Pull request by bevekashaivelt**
I resolved the conflicts. This looks good

### CODE REVIEW

**Comment by KFMDMSolutions** [comment]
image

what's the problem here?

your code still needs a little cleanup 

from what i saw there is two shouldOverrideUrlLoading methods
and there is missing some curly braces

**Comment by KFMDMSolutions** [comment]
image
this is in the wrong place too

**Comment by bevekashaivelt** [comment]
Interesting. I don't have the result.getType() code at all, where is it coming from? And EXTRA_URL is defined as a static string on line 66. Did you have uncommitted code on your machine? Also there aren't two shouldOverrideUrl methods in the code in the repository.

**Comment by KFMDMSolutions** [comment]
it should be in the menuited  method

which folder is the updated one 
the android cts 
or
the kfmdm one?

image

**Comment by bevekashaivelt** [comment]
kfmdm one

**Comment by bevekashaivelt** [comment]
it is missing that method, you want to add it manually?

**Comment by KFMDMSolutions** [comment]
> it is missing that method, you want to add it manually?

i"ll fix it 

but i tested the kfmdm one two days ago and it didn't send notifications 

did you update it?
this pull want in to the cts

**Comment by bevekashaivelt** [comment]
Yes, I updated it in this pull request from yesterday. It wasn't working at all? Or only when the device is unplugged?

**Comment by bevekashaivelt** [comment]
@mayim-chayim was saying that it doesn't work when on battery. I made some changes that will hopefully fix that, meanwhile test to see if it works while plugged in. Notifications will also be fetched whenever there is a change in the settings.

**Comment by KFMDMSolutions** [comment]
> Yes, I updated it in this pull request from yesterday. It wasn't working at all? Or only when the device is unplugged?

i used a emulator

i just added this branch  
https://github.com/KFMDMSolutions/Ivelt-Android-App/tree/test-notifacation

with the updated code 
i used the cts one 

tested it and it work's great  

check it out and let me me know if you approve it 
and i'll update it to the main branch 
or you disapprove it

**Comment by bevekashaivelt** [comment]
is it possible to merge the changes from the new pull request? There are a few changes that could help when the device is unplugged.

**Comment by bevekashaivelt** [comment]
otherwise i'm fine, maybe we should have a few people test it before we release.

**Comment by KFMDMSolutions** [comment]
> is it possible to merge the changes from the new pull request? There are a few changes that could help when the device is unplugged.

was this the changes?
https://github.com/KFMDMSolutions/Ivelt-Android-App/commit/ebedf4fa3fcb6df87f8b9415ae5657ea86143c2b
anything else?

**Comment by bevekashaivelt** [comment]
Nothing else.

**Comment by KFMDMSolutions** [comment]
> Nothing else.

thanks
i closed this pull 
https://github.com/KFMDMSolutions/Ivelt-Android-App/pull/16

is there anything in the main branch that needs to saved?
or i can delete it?

**Comment by bevekashaivelt** [comment]
I don't think so. Check from your side.

**Comment by bevekashaivelt** [comment]
I would rather merge notification branch into main, and then delete the notification branch. That's a better idea than deleting main.

**Comment by KFMDMSolutions** [comment]
> I would rather merge notification branch into main, and then delete the notification branch. That's a better idea than deleting main.

אזוי האב איך געטוהן 
?איך האב עפעס געהארגעט

**Comment by mayim-chayim** [comment]
> i used a emulator

I am using the Battery status setting in the emulator

image

**Comment by bevekashaivelt** [comment]
> > I would rather merge notification branch into main, and then delete the notification branch. That's a better idea than deleting main.
> 
> אזוי האב איך געטוהן
> ?איך האב עפעס געהארגעט
ניין.

**Comment by bevekashaivelt** [comment]
> > i used a emulator
> 
> I am using the Battery status setting in the emulator
> 
> image

עס ארבייט נישט?

**Comment by KFMDMSolutions** [comment]
> > i used a emulator
> 
> I am using the Battery status setting in the emulator
> 
> image

די נייע ארבעט א מחי' אן קיין קאנפיגערעטשנס

**Comment by mayim-chayim** [comment]
> עס ארבייט נישט?

it does work

> די נייע ארבעט א מחי' אן קיין קאנפיגערעטשנס

it is configured as battery by default

**Comment by mayim-chayim** [comment]
when on battery and the settings are 
`paused false plugged_in_delay 0 battery 900000`
it doesn't work 

I am testing now if the opposite is also true

**Comment by KFMDMSolutions** [comment]
image
image

**Comment by mayim-chayim** [comment]
@KFMDMSolutions set the `plugged_in_delay ` to `Never` and check if it works

@bevekashaivelt I tested it both ways if one of the options is to `Never` it will not run

**Comment by mayim-chayim** [comment]
the problem is that `useForeground = true` if `Math.min(pluggedInDelay, batteryDelay) < 15 * MINUTE_IN_MILLIS)`
and subsequently `shouldUseWorkManager = fales` and `cancelWork` is being called

**Comment by KFMDMSolutions** [comment]
> the problem is that `useForeground = true` if `Math.min(pluggedInDelay, batteryDelay) < 15 * MINUTE_IN_MILLIS)`
> and subsequently `shouldUseWorkManager = fales` and `cancelWork` is being called

אויפן פאון ארבעט עס יא

**Comment by KFMDMSolutions** [comment]
> when on battery and the settings are
> `paused false plugged_in_delay 0 battery 900000`
> it doesn't work
> 
> I am testing now if the opposite is also true

@bevekashaivelt was this issue fixed?
so i can update the release

**Comment by bevekashaivelt** [comment]
Yes. It is fixed.

**Pull request merged**
